services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - '4001:4000'
    environment:
      DATABASE_URL: postgresql://postgres.hlzclxzzapywduzzwvfp:uKNeAlJ47YxJtgCI@aws-0-us-east-2.pooler.supabase.com:6543/postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  postgres_data: