services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - '4001:4000'
    environment:
      DATABASE_URL: ".env value for the databae url"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  postgres_data: